<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <AssemblyTitle>Portal</AssemblyTitle>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup>
        <IsWindowsBuildHost>$([MSBuild]::IsOSPlatform('Windows'))</IsWindowsBuildHost>
        <TargetsWindows Condition="$(RuntimeIdentifier.StartsWith('win'))">true</TargetsWindows>
        <TargetsWindows Condition="'$(RuntimeIdentifier)' == '' And $(RuntimeIdentifiers.StartsWith('win'))">true</TargetsWindows>
        <TargetsWindows Condition="'$(RuntimeIdentifier)' == '' And '$(RuntimeIdentifiers)' == '' And '$(IsWindowsBuildHost)' == 'true'">true</TargetsWindows>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetsWindows)' == 'true'">
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <HotAvaloniaAutoEnable>false</HotAvaloniaAutoEnable>
        <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/tiouoo/Portal</RepositoryUrl>
        <Description>Portal</Description>
        <PackageIcon>..\..\assets\Icon-Pattern-Shadow.png</PackageIcon>
        <PackageProjectUrl>portal.tiouo.cc</PackageProjectUrl>
        <PackageTags>Portal</PackageTags>
        <PackageVersion>1.0.0</PackageVersion>
        <Copyright>https://github.com/tiouoo/Portal</Copyright>
        <Authors>github.com/tiouoo/Portal</Authors>
        <ApplicationIcon>..\..\assets\Icon-Pattern.ico</ApplicationIcon>
        <Title>Portal</Title>

        <CFBundleName>Portal</CFBundleName>
        <CFBundleDisplayName>Portal</CFBundleDisplayName>
        <CFBundleIdentifier>cc.tiouoo.portal</CFBundleIdentifier>
        <CFBundleVersion>1.0.0</CFBundleVersion>
        <CFBundlePackageType>AAPL</CFBundlePackageType>
        <CFBundleSignature>Porta</CFBundleSignature>
        <CFBundleExecutable>Portal.Desktop</CFBundleExecutable>
        <CFBundleIconFile>Icon-Pattern-Shadow-Border.icns</CFBundleIconFile>
        <CFBundleShortVersionString>1.0</CFBundleShortVersionString>
        <NSPrincipalClass>NSApplication</NSPrincipalClass>
        <NSHighResolutionCapable>true</NSHighResolutionCapable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>

        <PackageReference Include="Avalonia.Markup.Xaml.Loader" PrivateAssets="All" Publish="True"/>

        <PackageReference Include="DotNet.Bundle"/>
        <PackageReference Include="HotAvalonia" PrivateAssets="All" Condition="'$(Configuration)' == 'Debug'"/>
        <PackageReference Include="SkiaSharp"/>
        <PackageReference Include="SkiaSharp.NativeAssets.Linux"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Portal\Portal.csproj"/>
        <ProjectReference Condition="'$(TargetsWindows)' == 'true'"
                          Include="..\Portal.Bedrock.Windows\Portal.Bedrock.Windows.csproj"/>
        <ProjectReference Condition="'$(TargetsLinux)' == 'true'"
                          Include="..\Portal.Bedrock.Linux\Portal.Bedrock.Linux.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="..\..\assets\Icon-Pattern.ico" Link="Assets\Icon-Pattern.ico"/>
        <AvaloniaResource Include="..\..\assets\Icon-Pattern.svg" Link="Assets\Icon-Pattern.svg"/>
        <AvaloniaResource Include="..\..\assets\Icon-Pattern-Shadow.png" Link="Assets\Icon-Pattern-Shadow.png"/>
        <AvaloniaResource Remove="publish\**"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Icon-Pattern-Shadow-Border.icns"/>
        <AvaloniaResource Include="..\..\assets\Icon-Pattern-Shadow-Border.icns" Link="Assets\Icon-Pattern-Shadow-Border.icns"/>
        <None Remove="publish\**"/>
    </ItemGroup>

    <ItemGroup>
        <AvaloniaXaml Remove="publish\**"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="publish\**"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Remove="publish\**"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Remove="publish\**"/>
    </ItemGroup>
</Project>
