<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/tiouoo/Portal</RepositoryUrl>
        <Description>Portal</Description>
        <PackageIcon>..\..\assets\Icon-Pattern-Shadow.png</PackageIcon>
        <PackageProjectUrl>portal.tiouo.cc</PackageProjectUrl>
        <PackageTags>Portal</PackageTags>
        <PackageVersion>0.0.0</PackageVersion>
        <Copyright>https://github.com/tiouoo/Portal</Copyright>
        <Authors>github.com/tiouoo/Portal</Authors>
        <ApplicationIcon>..\..\assets\Icon-Pattern.ico</ApplicationIcon>
        <Title>Portal</Title>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
        <EmbeddedResource Include="..\..\assets\conf\WikiEntries.txt">
            <Link>Assets\WikiEntries.txt</Link>
        </EmbeddedResource>
        <AvaloniaResource Include="..\..\assets\Icon-Pattern.ico" Link="Assets\Icon-Pattern.ico"/>
        <AvaloniaResource Include="..\..\assets\Icon-Pattern.png" Link="Assets\Icon-Pattern.png"/>
        <AvaloniaResource Include="..\..\assets\Icon-Pattern-Shadow.png" Link="Assets\Icon-Pattern-Shadow.png"/>
        <AvaloniaResource Include="..\..\assets\Icon-Pattern.svg" Link="Assets\Icon-Pattern.svg"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AsyncImageLoader.Avalonia"/>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.AvaloniaEdit"/>
        <PackageReference Include="Avalonia.Controls.ItemsRepeater"/>
        <PackageReference Include="Avalonia.Fonts.Inter"/>
        <PackageReference Include="Avalonia.Markup.Xaml.Loader" PrivateAssets="All" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="HotAvalonia" Condition="'$(Configuration)' == 'Debug'"/>
        <PackageReference Include="Irihi.Lingua"/>
        <PackageReference Include="SkiaSharp"/>
        <PackageReference Include="Tomlyn"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\module\Tio.Avalonia.Standard\src\Tio.Avalonia.Standard.Tab\Tio.Avalonia.Standard.Tab.csproj"/>
        <ProjectReference Include="..\..\module\Tio.Avalonia.Standard\src\Tio.Avalonia.Standard\Tio.Avalonia.Standard.csproj"/>
        <ProjectReference Include="..\Portal.Core\Portal.Core.csproj"/>
        <ProjectReference Include="..\Portal.LitematicaViewer\LitematicaViewer.csproj"/>
        <ProjectReference Include="..\Portal.Localization\Portal.Localization.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\Pages\ToolsPages\MultiplayerPages\RedstoneMultiplayerPage.axaml.cs">
        <DependentUpon>RedstoneMultiplayerPage.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Pages\ToolsPages\MultiplayerPages\TerracottaMultiplayerPage.axaml.cs">
        <DependentUpon>TerracottaMultiplayerPage.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Pages\ToolsPages\MultiplayerPages\MultiplayerPage.axaml.cs">
        <DependentUpon>MultiplayerPage.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Pages\ToolsPages\MultiplayerPages\MultiplayerPortDialog.axaml.cs">
        <DependentUpon>MultiplayerPortDialog.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Pages\ToolsPages\MultiplayerPages\MultiplayerContentPage.axaml.cs">
        <DependentUpon>MultiplayerContentPage.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
    
</Project>
