<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Portal.Preload.Net</AssemblyName>
    <RootNamespace>Portal.Bedrock.Preload</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <IsAotCompatible>true</IsAotCompatible>
    <Version>0.0.0</Version>
    <StripSymbols>true</StripSymbols>
    <NoWarn>$(NoWarn);CA2255</NoWarn>
    <EnableDefaultItems>true</EnableDefaultItems>
  </PropertyGroup>

  <Target Name="CopyNativeDllToRepo" AfterTargets="Publish">
    <Copy SourceFiles="$(PublishDir)$(AssemblyName).dll"
          DestinationFolder="$(MSBuildProjectDirectory)"
          SkipUnchangedFiles="false" />
    <Message Importance="high"
             Text="[Portal.Bedrock.Preload] 已复制原生 dll 到 $(MSBuildProjectDirectory)\$(AssemblyName).dll" />
  </Target>

</Project>
