#pragma once

#define PRELOADCPP_VERSION_MAJOR 0
#define PRELOADCPP_VERSION_MINOR 0
#define PRELOADCPP_VERSION_PATCH 0
#define PRELOADCPP_VERSION_BUILD 0
#define PRELOADCPP_VERSION "0.0.0"
#define PRELOADCPP_COMMIT_HASH "unknown"
