namespace Portal.Bedrock.Core;

public static class SoapApi
{
	public const string SoapContentType = "application/soap+xml; charset=utf-8";

	public static readonly string DeviceAttributes = "E:BranchReadinessLevel=CBB&amp;DchuNvidiaGrfxExists=1&amp;ProcessorIdentifier=Intel64%20Family%206%20Model%2063%20Stepping%202&amp;CurrentBranch=rs4_release&amp;DataVer_RS5=1942&amp;FlightRing=Retail&amp;AttrDataVer=57&amp;InstallLanguage=en-US&amp;DchuAmdGrfxExists=1&amp;OSUILocale=en-US&amp;InstallationType=Client&amp;FlightingBranchName=&amp;Version_RS5=10&amp;UpgEx_RS5=Green&amp;GStatus_RS5=2&amp;OSSkuId=48&amp;App=WU&amp;InstallDate=1529700913&amp;ProcessorManufacturer=GenuineIntel&amp;AppVer=10.0.17134.471&amp;OSArchitecture=AMD64&amp;UpdateManagementGroup=2&amp;IsDeviceRetailDemo=0&amp;HidOverGattReg=C%3A%5CWINDOWS%5CSystem32%5CDriverStore%5CFileRepository%5Chidbthle.inf_amd64_467f181075371c89%5CMicrosoft.Bluetooth.Profiles.HidOverGatt.dll&amp;IsFlightingEnabled=0&amp;DchuIntelGrfxExists=1&amp;TelemetryLevel=1&amp;DefaultUserRegion=244&amp;DeferFeatureUpdatePeriodInDays=365&amp;Bios=Unknown&amp;WuClientVer=10.0.17134.471&amp;PausedFeatureStatus=1&amp;Steam=URL%3Asteam%20protocol&amp;Free=8to16&amp;OSVersion=10.0.17134.472&amp;DeviceFamily=Windows.Desktop";

	public const string FE3FileUrl = "<s:Envelope xmlns:a=\"http://www.w3.org/2005/08/addressing\" xmlns:s=\"http://www.w3.org/2003/05/soap-envelope\">\n\t<s:Header>\n\t\t<a:Action s:mustUnderstand=\"1\">http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService/GetExtendedUpdateInfo2</a:Action>\n\t\t<a:MessageID>urn:uuid:5754a03d-d8d5-489f-b24d-efc31b3fd32d</a:MessageID>\n\t\t<a:To s:mustUnderstand=\"1\">https://fe3.delivery.mp.microsoft.com/ClientWebService/Client.asmx/secured</a:To>\n\t\t<o:Security s:mustUnderstand=\"1\" xmlns:o=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\">\n\t\t\t<Timestamp xmlns=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\">\n\t\t\t\t<Created>\n\t\t\t\t</Created>\n\t\t\t\t<Expires>\n\t\t\t\t</Expires>\n\t\t\t</Timestamp>\n\t\t\t<wuws:WindowsUpdateTicketsToken wsu:id=\"ClientMSA\" xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\" xmlns:wuws=\"http://schemas.microsoft.com/msus/2014/10/WindowsUpdateAuthorization\">\n\t\t\t\t<TicketType Name=\"AAD\" Version=\"1.0\" Policy=\"MBI_SSL\">\n\t\t\t\t</TicketType>\n\t\t\t</wuws:WindowsUpdateTicketsToken>\n\t\t</o:Security>\n\t</s:Header>\n\t<s:Body>\n\t\t<GetExtendedUpdateInfo2 xmlns=\"http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService\">\n\t\t\t<updateIDs>\n\t\t\t\t<UpdateIdentity>\n\t\t\t\t\t<UpdateID>\n\t\t\t\t\t</UpdateID>\n\t\t\t\t\t<RevisionNumber>1</RevisionNumber>\n\t\t\t\t</UpdateIdentity>\n\t\t\t</updateIDs>\n\t\t\t<infoTypes>\n\t\t\t\t<XmlUpdateFragmentType>FileUrl</XmlUpdateFragmentType>\n\t\t\t</infoTypes>\n\t\t\t<deviceAttributes>\n\t\t\t</deviceAttributes>\n\t\t</GetExtendedUpdateInfo2>\n\t</s:Body>\n</s:Envelope>";
}
