<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Portal.Bedrock.Linux</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Portal.Bedrock.Core\Portal.Bedrock.Core.csproj" />
    <ProjectReference Include="..\Portal.Bedrock.Standard\Portal.Bedrock.Standard.csproj" />
  </ItemGroup>

</Project>
