name: publish/nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "00 20 * * *"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version_json: ${{ steps.meta.outputs.json }}
      app_version: ${{ steps.meta.outputs.app_version }}
      commit: ${{ steps.meta.outputs.commit_hash }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach --recursive 'git fetch origin main && git checkout -B main origin/main'

      - name: Generate Meta and JSON
        id: meta
        run: |
          BASE_VERSION=$(cat ./src/version.txt | tr -d '[:space:]')
          Y_FULL=$(TZ='Asia/Shanghai' date +'%Y')
          MD=$(TZ='Asia/Shanghai' date +'%m%d')
          HM=$(TZ='Asia/Shanghai' date +'%H%M')
          FULL_TIMESTAMP="${Y_FULL}${MD}${HM}"
          START_EPOCH=$(date -d "2026-01-01 00:00:00" +%s)
          NOW_EPOCH=$(date +%s)
          TOTAL_HOURS=$(( (NOW_EPOCH - START_EPOCH) / 3600 ))
          APP_VERSION="${BASE_VERSION}.${TOTAL_HOURS}"
          COMMIT_HASH=$(git rev-parse --short=6 HEAD)
          BUILD_TIME=$(TZ='Asia/Shanghai' date -Iseconds)
          JSON_STRING="{\"type\":\"commit\",\"build-time\":\"${BUILD_TIME}\",\"action\":\"${{ github.run_id }}\",\"commit\":\"${COMMIT_HASH}\",\"version\":\"${BASE_VERSION}\",\"timestamp\":\"${FULL_TIMESTAMP}\"}"
          echo "json=${JSON_STRING}" >> $GITHUB_OUTPUT
          echo "app_version=${APP_VERSION}" >> $GITHUB_OUTPUT
          echo "commit_hash=${COMMIT_HASH}" >> $GITHUB_OUTPUT

  appImage:
    runs-on: ubuntu-22.04
    needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach --recursive 'git fetch origin main && git checkout -B main origin/main'

      - name: Write CI Config
        run: echo '${{ needs.prepare.outputs.version_json }}' > ./src/version-ci.txt

      - name: Dependency
        run: |
          dotnet tool install -g KuiperZone.PupNet --version 1.8.0
          sudo apt-get update && sudo apt-get install -y fuse

      - name: Build-AppImage
        run: |
          cd ./src/Portal.Desktop
          pupnet --runtime linux-x64 --kind appimage -o Portal.linux.x64.AppImage -y --app-version ${{ needs.prepare.outputs.app_version }}
          pupnet --runtime linux-arm --kind appimage -o Portal.linux.arm.AppImage -y --app-version ${{ needs.prepare.outputs.app_version }}
          pupnet --runtime linux-arm64 --kind appimage -o Portal.linux.arm64.AppImage -y --app-version ${{ needs.prepare.outputs.app_version }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: src/Portal.Desktop/Deploy/OUT/Portal.linux.*.AppImage

  win-exe:
    runs-on: windows-latest
    needs: prepare
    strategy:
      matrix:
        rid: [win-x64, win-x86, win-arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach --recursive "git fetch origin main && git checkout -B main origin/main"
        shell: bash

      - name: Write CI Config
        run: echo '${{ needs.prepare.outputs.version_json }}' > ./src/version-ci.txt
        shell: bash

      - name: Build & Package
        shell: pwsh
        run: |
          cd ./src/Portal.Desktop
          New-Item -ItemType Directory -Force -Path "../../dist"
          dotnet restore -r ${{ matrix.rid }}
          dotnet publish -c Release -r ${{ matrix.rid }} /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:IncludeNativeLibrariesForSelfExtract=true /p:SelfContained=true /p:Version=${{ needs.prepare.outputs.app_version }} -o "../../dist" -p:DebugType=none -p:DebugSymbols=false
          cd "../../dist"
          Rename-Item -Path "Portal.Desktop.exe" -NewName "Portal.${{ matrix.rid }}.executable.exe" -Force
          Compress-Archive -Path "Portal.${{ matrix.rid }}.executable.exe" -DestinationPath "../Portal.${{ matrix.rid }}.executable.zip" -Force

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win-exe-${{ matrix.rid }}-artifacts
          path: ./Portal.*.zip

  win-installer:
    runs-on: windows-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach --recursive "git fetch origin main && git checkout -B main origin/main"
        shell: bash

      - name: Dependencies
        run: |
          choco install innosetup -y
          dotnet tool install -g KuiperZone.PupNet --version 1.8.0

      - name: Chinesize-InnoSetup
        run: Copy-Item "./assets/ChineseSimplified.isl" "C:\Program Files (x86)\Inno Setup 6\Default.isl" -Force

      - name: Write CI Config
        run: echo '${{ needs.prepare.outputs.version_json }}' > ./src/version-ci.txt
        shell: bash

      - name: Build
        run: |
          cd ./src/Portal.Desktop
          pupnet -r win-x64 -k setup -y -o Portal.win.x64.installer.exe --app-version ${{ needs.prepare.outputs.app_version }}
          pupnet -r win-x86 -k setup -y -o Portal.win.x86.installer.exe --app-version ${{ needs.prepare.outputs.app_version }}
          pupnet -r win-arm64 -k setup -y -o Portal.win.arm64.installer.exe --app-version ${{ needs.prepare.outputs.app_version }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win-installer-artifacts
          path: src/Portal.Desktop/Deploy/OUT/Portal.win.*.installer.exe

  mac-dmg:
    runs-on: macos-latest
    needs: prepare
    strategy:
      matrix:
        rid: [osx-x64, osx-arm64]
        include:
          - rid: osx-x64
            dmg_arch: x64
          - rid: osx-arm64
            dmg_arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach --recursive 'git fetch origin main && git checkout -B main origin/main'

      - name: Write CI Config
        run: echo '${{ needs.prepare.outputs.version_json }}' > ./src/version-ci.txt

      - name: Build macOS App
        run: |
          cd ./src/Portal.Desktop
          dotnet restore -r ${{ matrix.rid }}
          dotnet msbuild -t:BundleApp -p:RuntimeIdentifier=${{ matrix.rid }} -property:Configuration=Release -p:SelfContained=true
          cp "../../assets/Icon-Pattern-Shadow-Border.icns" "./bin/Release/net10.0/${{ matrix.rid }}/publish/Portal.app/Contents/Resources/"

      - name: Package APP to ZIP
        run: |
          cd ./src/Portal.Desktop/bin/Release/net10.0/${{ matrix.rid }}/publish/
          zip -r ../../../../../../../Portal.osx.mac.${{ matrix.dmg_arch }}.app.zip Portal.app

      - name: Build DMG
        uses: L-Super/create-dmg-actions@v1.0.3
        with:
          dmg_name: "Portal.osx.mac.${{ matrix.dmg_arch }}"
          src_dir: "./src/Portal.Desktop/bin/Release/net10.0/${{ matrix.rid }}/publish/Portal.app"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: osx-${{ matrix.dmg_arch }}-artifacts
          path: |
            ./Portal.osx.mac.${{ matrix.dmg_arch }}.dmg
            ./Portal.osx.mac.${{ matrix.dmg_arch }}.app.zip

  publish:
    needs: [prepare, appImage, win-exe, win-installer, mac-dmg]
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./Portal.Release/
          merge-multiple: true

      - name: List Files
        run: ls -la ./Portal.Release/

      - name: Publish Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "build-nightly-${{ needs.prepare.outputs.app_version }}-${{ github.run_id }}-${{ needs.prepare.outputs.commit }}"
          automatic_release_tag: "publish-nightly"
          prerelease: false
          files: |
            ./Portal.Release/*.exe
            ./Portal.Release/*.dmg
            ./Portal.Release/*.zip
            ./Portal.Release/*.AppImage